name: CrudJS Lastest Build
on:
    push:
        branches:
            - master
jobs:
    deploy:
        name: Deploy lastest
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build --if-present
            - name: Deploy lastest build
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: lastest
                FOLDER: .
            - name: Deploy to github pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: gh-pages
                FOLDER: docs
