name: Release CrudJS
on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        name: Release GitHub Actions
        runs-on: ubuntu-latest
        steps:
            - uses: technote-space/release-github-actions@v4
              with:
                  PACKAGE_MANAGER: npm
                  BUILD_COMMAND_TARGET: build:js
                  CLEAN_TARGETS: .[!.]*, *.lock, *-lock.json 
