name: Release CrudJS
on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        name: Release GitHub Actions
        runs-on: ubuntu-latest
        steps:
            - uses: technote-space/release-github-actions@v4
              with:
                  BUILD_COMMAND_TARGET: npm run build:js
                  PACKAGE_MANAGER: npm
                  COMMIT_MESSAGE: Release build
